arcana-network/website

.gitignore, components/lib/VText.stories.js, package-lock.json, package.json
Integrates storybook using the [`@nuxtjs/storybook`](https://storybook.nuxtjs.org/) package.
=> Setup storybook

.husky/commit-msg, commitlint.config.js, package-lock.json, package.json
We can introduce `commitlint` later if needed.
=> Remove `commitlint` packages and config

components/lib/VButton.vue, components/lib/VLabel.vue, components/lib/VRadioGroup.vue, components/lib/VTextField.vue
1. Added whitespace nowrap to button to avoid content inside button from wrapping on mobile devices
2. Updated transform property of link button to create a click effect while active
3. Updated font size of label for smaller screens
4. Added checked property for radiobuttons so they update their state when they're clicked
5. Added input type number for textfield so it can accept numeric inputs
=> Added button, radiogroup and textfield updates

components/lib/VHeader.vue
1. Changed gap between header links to vw (viewport width) instead of rem so they create space according to size of viewport
2. Changed opacity to transform scale on click of menu link so it creates a click effect
=> Fixed layout issues

components/lib/VText.vue
Removed default from props and moved it to style tag so it doesn't override styling provided by parent component
Also added optional chaining while checking existence of props
=> Updated props for vtext

components/lib/VStack.vue
1. Added support for medium viewport devices in props
2. Added row-reverse and column reverse flex values in direction props
3. Added variables for responsive handling of gaps
=> Layout helpers/stack layout fixes

components/art/NodeGrid.stories.js, components/art/NodeGrid.vue, components/home/HeroSection.vue
Adds an animated version of the homepage header image.
=> AR-394 - Animations: Homepage header

components/lib/VButton.vue
Changes as requested by Arvindh, merging this to home-page-changes instead of dev as home-page changes have a lot of changes
=> Reduced border-radius, added transition to button

netlify.toml
Changes in the `netlify.toml` file.
=> Adds config for testnet subdomain

components/testnet/TestnetBuildOverview.vue, components/testnet/TestnetBuildSupport.vue, components/testnet/TestnetBuildUseCases.vue, components/testnet/TestnetOverviewSection.vue
Content changes on the Testnet page.
=> AR-558: Testnet content changes

assets/images/revoke.svg, assets/images/share.svg, components/lib/VChip.vue, components/lib/VHeader.vue, components/lib/VList.vue, components/lib/VStack.vue, components/lib/VTabs.vue, components/testnet/TestnetBugBountyOverview.vue, components/testnet/TestnetBugBountyPrizes.vue, components/testnet/TestnetBugBountyRules.vue, components/testnet/TestnetBugBountyScope.vue, components/testnet/TestnetBugBountySection.vue, components/testnet/TestnetBuildOverview.vue, components/testnet/TestnetBuildUseCases.vue, components/testnet/TestnetFooter.vue, components/testnet/TestnetHeader.vue, components/testnet/TestnetHeroSection.vue, components/testnet/TestnetOverviewSection.vue, components/testnet/TestnetQuickLinks.vue, pages/testnet.vue
**Changes**
- Adds the Bug Bounty section
- Adds content and design changes
=> AR-558: Testnet bug bounty section

components/AppFooter.vue, components/about/TeamMember.vue, components/home/HeroSection.vue, components/home/NewsAndMedia.vue, components/testnet/TestnetBuildSupport.vue, pages/privacy.vue
- Replace link to twitter with discord.
- Fix target attribute values in `a` elements.
=> Hero social link changes

components/about/OurTeam.vue
Resolves [AR-1011](https://team-1624093970686.atlassian.net/browse/AR-1011).
=> Correction in Prof. Bill's title

components/about/OurInvestors.vue
=> Small designation change

components/AppCopyright.vue
**Changes**
- Switch to using `new Date().getFullYear()` in copyright line
Resolves [AR-1160](https://team-1624093970686.atlassian.net/browse/AR-1160).
=> Update year in copyright

.github/PULL_REQUEST_TEMPLATE.md, .gitignore
Continues [AR-860](https://team-1624093970686.atlassian.net/jira/software/projects/AR/boards/1?assignee=5dc117e57dcf390c61844cda&selectedIssue=AR-860).
- Adds a template for pull requests.
- Removes `.github` directory from `.gitignore`.
=> Add a pull request template

components/tech/RoadmapList.vue
- [AR-1508](https://team-1624093970686.atlassian.net/browse/AR-1508)
Added 2022 roadmap content.
=> Update roadmap content

netlify.toml
- [AR-1125](https://team-1624093970686.atlassian.net/browse/AR-1125) Add redirect rule for the Ghost blog
cc: @lakshmikanthfang
=> Add redirect rules for Ghost blog

components/AppBanner.vue, components/AppHeader.vue, components/lib/VButton.vue, components/lib/VHeader.vue, layouts/page.vue
- [AR-2760](https://team-1624093970686.atlassian.net/browse/AR-2760)
- Change button border radius and gradient color
- Change VHeader, include CTA button in nav
- Remove alpha testnet banner
- Change CTA text from Technical paper to Start Building and point CTA to [Developer Dashboard](https://dashboard.arcana.network)
- Remove unused styles
=> Change header cta

pages/index.vue
- [AR-2763](https://team-1624093970686.atlassian.net/browse/AR-2763)
Remove the following sections
- Our Investors
- Our Partners
- Interoperability
- Community
- Newsletter
=> Remove sections that are not required in home page

assets/images/arcana-overview-access.svg, assets/images/arcana-overview-auth.svg, assets/images/arcana-overview-store.svg, components/AppSectionDescriptor.vue, components/home/OurServices.vue, pages/index.vue
- [AR-2762](https://team-1624093970686.atlassian.net/browse/AR-2762)
- Rename features to Our Services
- Update Our services page
=> Services section

components/home/HeroSection.vue
- [AR-3253](https://team-1624093970686.atlassian.net/browse/AR-3253)
- Change hero text
- Update sizing of elements of Video Thumbail
=> Update Hero content and adjust size of video container

components/AppFooter.vue
- [AR-3326](https://team-1624093970686.atlassian.net/browse/AR-3326)
=> Update blog link and target in footer

components/AppBanner.vue
Resolves [AR-2459](https://team-1624093970686.atlassian.net/browse/AR-3459).
Merge a few minutes before 12pm. Change the blog link before merging.
=> [Hotfix] Add post-launch banner

components/home/OurServices.vue
Quick fix
Fixed Typo
Before:
After:
=> [Quick fix] - typo

components/careers/OpenPositions.vue
- [AR-3460](https://team-1624093970686.atlassian.net/browse/AR-3460)
1. Remove Irrelevant Job Postings from Website Careers section.
=> [AR-3460] - Remove Irrelevant Job Postings from Website

components/home/Newsletter.vue, pages/index.vue
- [AR-3436](https://team-1624093970686.atlassian.net/browse/AR-3436)
- Clear newsletter field after success
- Add newsletter in home
=> Add newsletter in home

components/home/Newsletter.vue, pages/index.vue
- [AR-3436](https://team-1624093970686.atlassian.net/browse/AR-3436)
- Clear newsletter field after success
- Add newsletter in home
=> [Hotfix] Add newsletter in home

components/tech/Technology.vue
- [AR-3422](https://team-1624093970686.atlassian.net/browse/AR-3422)
- Removed title from hero section of tech page
=> Remove title from hero section of tech page

components/home/Testimonials.vue
- [AR-3420](https://team-1624093970686.atlassian.net/browse/AR-3420)
- Fix font-weight of testimonial content
- Fix spacing between testimonial author name and his designation
Before
After
=> Fix testimonial typography

components/about/OurTeam.vue, components/home/Newsletter.vue, components/lib/VDropdown.vue, components/lib/VTextField.vue
- [AR-3927](https://team-1624093970686.atlassian.net/browse/AR-3927)
- Updated Manish's twitter handle
- Reduced size of textfield and dropdown on smaller screens
- Fixed z-index of `1000's and counting` text in Newsletter section
- Removed html comments
Before
After
=> Update newsletter input and Manish's twitter id

components/MainnetFooter.vue, components/MainnetHeader.vue, pages/mainnet.vue
- [AR-5062](https://team-1624093970686.atlassian.net/browse/AR-5062)
1. Implemented Header based on design
2. Reduced margin in footer to creating padding at the sides for small screens.
3. Set fixed width for content.
=> [AR-5062] Main-net coming soon page fixes
